spring.application.name=spring-security

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/spring_security?options=-c%20TimeZone=Asia/Kolkata
spring.datasource.username=postgres
spring.datasource.password=password

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true